Add IDynamicRegexRouteConstraint
lokiworld/Elastic.Routing pull request #2
Opened 2018-08-16 14:47 UTC by sanacommerce

2018-08-20 11:22 UTC, dmoskalyk requested changes

2018-08-20 11:22 UTC, dmoskalyk commented on src/Elastic.Routing/ElasticRoute.cs
> +        private struct InnerData
Change to class, rename to "ParsedRoutePattern" and extract into a separate file with "internal" access modifier.

2018-08-20 11:22 UTC, dmoskalyk commented on src/Elastic.Routing/IDynamicRegexRouteConstraint.cs
> +        /// An evenet which occurs when <see cref="IRegexRouteConstraint.Pattern"/> is changed.
"evenet" => "event"

2018-08-20 11:22 UTC, dmoskalyk commented on src/Elastic.Routing/IDynamicRegexRouteConstraint.cs
> +    /// An interface representing a route constraint with regular expression pattern which can be changed on runtime.
"on runtime" => "at runtime"

2018-08-20 11:22 UTC, dmoskalyk commented on src/Elastic.Routing/IRegexRouteConstraint.cs
>      /// An interface representing a route constraint which can also provide a regular expression pattern in addition to custom constrain logic.
Please, fix also this mistyping:
"constrain" => "constraint"

2018-08-20 11:22 UTC, dmoskalyk commented on src/Elastic.Routing/ElasticRoute.cs
> +        private InnerData PatternData;
Rename "PatternData" field to "parsedPattern". With the new name it will give more understanding what is it about and, according to guidelines, private field names should start with lowercase.

2018-08-20 11:50 UTC, sanacommerce commented on src/Elastic.Routing/ElasticRoute.cs
> +        private struct InnerData
Done

2018-08-20 15:08 UTC, dmoskalyk approved these changes

2018-08-22 08:05 UTC, dmoskalyk approved these changes

2018-08-22 08:05 UTC, merged